# Generated by Django 4.0.2 on 2022-02-28 02:11

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=store.models.get_image_path),
        ),
    ]
