# Generated by Django 4.0.1 on 2022-03-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(default='Conversation', max_length=30),
        ),
    ]
