# Generated by Django 4.0.1 on 2022-03-07 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0002_conversation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='members',
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='userGroup',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.usergroup'),
        ),
    ]
