# Generated by Django 4.0.1 on 2022-02-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_profile_alter_conversation_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='displayPoints',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='displayPurchases',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
    ]
